project:
  type: website

website:
  title: "Scar Winter Kelsey | ScarData"
  navbar:
    title: false
    search: true
    pinned: true
    right: 
      - href: index.qmd
        text: Home
      - about.qmd
      
      - href: projects.qmd
        text: Projects
        
      - href: resources.qmd
        text: Resources
    
format:
  html:
    theme: 
      light: jolla
      dark: solar
    css: styles.css

editor: visual