project:
  type: website

website:
  title: "Scar Winter Kelsey | ScarData"
      favicon: image
   # google-analytics:
   #  tracking-id:
   #  anonymize-ip: true
  navbar:
    title: false
    logo: ScarData logo
    logo-alt: accessibility label
    search: true
    pinned: true
    right: 
      - href: index.qmd
       text: Home
    menu:
      - about.qmd
      - project-ibis.qmd
      - yrbs-data-management.qmd
      - pandas.qmd
      - resources.qmd
    
format:
  html:
    theme: 
      light: jolla
      dark: solar
    css: styles.css

editor: visual