project:
  type: website

website:
  title: "Scar Winter Kelsey | ScarData"
  site-url: https://www.scardata.com
  google-analytics: G-3F6HDZT979
  open-graph: true
  cookie-consent:
        type: express
        style: simple
        palette: dark
#  favicon: 
  navbar:
    title: false
    search: true
    pinned: true
    right: 
      - href: index.qmd
        text: Home
      
      - href: projects.qmd
        text: Projects
        
      #- href: resources.qmd
      #  text: Resources
        
      - href: sharing-ideas.qmd
        text: Sharing Ideas
    
format:
  html:
    theme: 
      light: lux.scss
      dark: luxdark.scss
    link-external-newwindow: true
    smooth-scroll: true
    css: 
    - styles.scss
    code-copy: true
    code-overflow: wrap


editor: visual
