project:
  type: website

website:
  title: "Scar Winter Kelsey | ScarData"
  site-url: https://www.scardata.com
  navbar:
    title: false
    search: true
    pinned: true
    right: 
      - href: index.qmd
        text: Home
      - about.qmd
      
      - href: projects.qmd
        text: Projects
        
      - href: resources.qmd
        text: Resources
        
      - href: sharing-ideas.qmd
        text: Sharing Ideas
    
format:
  html:
    theme: 
      - lux.scss
    link-external-newwindow: true
    smooth-scroll: true
    
editor: visual
