project:
  type: website

website:
  title: "Scar Winter Kelsey | ScarData"
  navbar:
    search: true
    pinned: true
    text: "Projects"
    menu:
      - project-ibis.qmd
      - yrbs-data-management.qmd
      - pandas.qmd

format:
  html:
    theme: jolla
    css: styles.css
    toc: true

editor: visual