project:
  type: website

website:
  title: "Scar Winter Kelsey | ScarData"
  site-url: https://www.scardata.com
  google-analytics: G-3F6HDZT979
  open-graph: true
  cookie-consent:
        type: express
        style: simple
        palette: dark
  favicon: images/snowflake.png
  navbar:
    title: false
    search: true
    pinned: true
    right: 
      - href: index.qmd
        text: Home
      
      - href: projects.qmd
        text: Projects
        
      #- href: resources.qmd
      #  text: Resources
        
      - href: sharing-ideas.qmd
        text: Sharing Ideas
      
      - text: Reach out
        menu:
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/scar-wk
            target: _blank
          - icon: envelope
            text: email
            href: mailto:scardata@gmail.com
            target: _blank

  page-footer:
    left: © 2025 Scar Winter Kelsey
    right: This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/samanthacsik/samanthacsik.github.io){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
    
format:
  html:
    theme: 
      light: lux.scss
      dark: luxdark.scss
    link-external-newwindow: true
    smooth-scroll: true
    css: 
    - styles.scss
    code-copy: true
    code-overflow: wrap


editor: visual
