[build]
  command = "./build.sh"
  publish = "_site"
  
  # Environment variables (optional)
  [build.environment]
    # Set the Quarto version (optional)
    QUARTO_VERSION = "1.4.0"

    # Set Node.js version (if your project uses Node.js for custom scripts)
    NODE_VERSION = "18"

# Redirects for single-page applications (SPA) or custom routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ignore Puppeteer and Node.js dependencies
  ignore = "node_modules"

  [[plugins]]
  package = "netlify-plugin-quarto"