[build]
  # Install Quarto and build the site
  command = "curl -LO https://quarto.org/download/latest/quarto-linux-amd64.deb && sudo dpkg -i quarto-linux-amd64.deb && quarto render"

  # Publish the output directory (default is `_site` for Quarto)
  publish = "_site"
  
  # Environment variables (optional)
  [build.environment]
    # Set the Quarto version (optional)
    QUARTO_VERSION = "1.4.0"

    # Set Node.js version (if your project uses Node.js for custom scripts)
    NODE_VERSION = "18"

# Redirects for single-page applications (SPA) or custom routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200